openapi: 3.0.1
info:
  title: Express OpenAPI Example
  version: 1.0.0

paths:
  /hello:
    get:
      summary: Say Hello
      operationId: sayHello
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello, World!"
